name: DeviceFarm Report

on:
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}    

      - name: Start Device Farm run
        id: run
        run: |
          RUN_ARN=$(aws devicefarm schedule-run \
            --project-arn YOUR_PROJECT_ARN \
            --app-arn YOUR_APP_ARN \
            --device-pool-arn YOUR_POOL_ARN \
            --test type=APPIUM_NODE,testPackageArn=YOUR_TEST_PACKAGE_ARN \
            --query 'run.arn' --output text)

          echo "RUN_ARN=$RUN_ARN" >> $GITHUB_OUTPUT   

       - name: Wait for Device Farm
        run: |
          STATUS="PENDING"
          while [[ "$STATUS" != "COMPLETED" && "$STATUS" != "ERRORED" ]]; do
            STATUS=$(aws devicefarm get-run \
              --arn ${{ steps.run.outputs.RUN_ARN }} \
              --query 'run.status' --output text)
            echo "Status: $STATUS"
            sleep 30
          done   

       - name: Download Device Farm output
        run: |
          mkdir -p reports
          URL=$(aws devicefarm list-artifacts \
            --arn ${{ steps.run.outputs.RUN_ARN }} \
            --type FILE \
            --query 'artifacts[0].url' \
            --output text)

          curl "$URL" -o reports/devicefarm-log.txt    

      - name: Crear carpeta de reportes
        run: mkdir -p reports

      - name: Copiar archivo de Device Farm
        run: cp "device-farm-output.txt" reports/devicefarm-log.txt

      - name: Instalar dependencias
        run: npm install

      - name: Generar reporte HTML
        id: generate-report
        run: |
          node scripts/generate-report.js \
          reports/devicefarm-log.txt \
          reports/devicefarm-report.html

      - name: Subir artefacto del reporte
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: devicefarm-report
          path: reports/devicefarm-report.html

      - name: Enviar link del reporte a Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "channel": "#prueba-app",
              "text": "*${{ steps.generate-report.outputs.SLACK_TEXT }}*\n\n:iphone: Dispositivo: Android\n:stopwatch: Duración total: ${{ steps.generate-report.outputs.DURATION }}\n:file_folder: Archivos ejecutados: ${{ steps.generate-report.outputs.FILECOUNT }}\n:point_right: <${{ steps.upload.outputs.artifact-url }}|*Ver reporte completo*>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
